# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: publish.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'publish.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rpublish.proto\x12\tGrpcAgent\"0\n\x0ePublishRequest\x12\r\n\x05topic\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\"!\n\x0cPublishReply\x12\x11\n\tisSuccess\x18\x01 \x01(\x08\x32Q\n\tPublisher\x12\x44\n\x0ePublishMessage\x12\x19.GrpcAgent.PublishRequest\x1a\x17.GrpcAgent.PublishReplyB\x0c\xaa\x02\tGrpcAgentb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'publish_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\tGrpcAgent'
  _globals['_PUBLISHREQUEST']._serialized_start=28
  _globals['_PUBLISHREQUEST']._serialized_end=76
  _globals['_PUBLISHREPLY']._serialized_start=78
  _globals['_PUBLISHREPLY']._serialized_end=111
  _globals['_PUBLISHER']._serialized_start=113
  _globals['_PUBLISHER']._serialized_end=194
# @@protoc_insertion_point(module_scope)
